# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20160218_2251'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='activity',
            index_together=set([('about_content_type', 'about_id'), ('created_user', 'action', 'privacy', 'id')]),
        ),
    ]
