# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20160219_1633'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='activity',
            index_together=set([('created_user', 'action', 'privacy', 'created_dttm'), ('about_id', 'about_content_type', 'created_dttm')]),
        ),
    ]
