# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20160223_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
    ]
